using System.CodeDom.Compiler;

namespace Temperature_Converter
{
    public partial class TemperatureConverter : Form
    {
        public TemperatureConverter()
        {
            InitializeComponent();
        }
        //code generated by Visual Studio
        private void Form1_Load(object sender, EventArgs e)
        {
        }

        private void tbFarenheit_TextChanged(object sender, EventArgs e)
        {
        }

        private void tbCelcius_TextChanged(object sender, EventArgs e)
        {
        }

        private void tbKelvin_TextChanged(object sender, EventArgs e)
        {
        }

        //Method created to delete the content of the fields.
        private void clearFields()
        {
            tbFarenheit.Text = "";
            tbCelsius.Text = "";
            tbKelvin.Text = "";
        }

        //Verify if only one field is filled. For every field that has data, count variable will be added 1 to the current value. If it's more than 1, returns a false.
        private bool onlyOneTextfieldFilled()
        {
            int count = 0;
            if (!string.IsNullOrEmpty(tbFarenheit.Text))
            {
                count++;
            }
            if (!string.IsNullOrEmpty(tbCelsius.Text))
            {
                count++;
            }
            if (!string.IsNullOrEmpty(tbKelvin.Text))
            {
                count++;
            }

            return count == 1;
        }
        //Method will convert a value from Farenheit to Celsius and Kelvin
        private void convertFarenheit()
        {
            //Variable declaration
            double farenheit = 0;
            double celsius = 0;
            double kelvin = 0;

            //double.Parse instruction will convert content from the text field to a double type number
            farenheit = double.Parse(tbFarenheit.Text);


            //Math operations are executed to convert temperature from Farenheit to Celsius and Kelvin
            celsius = (farenheit - 32) / 1.8;
            //Math.Round limits the decimal position to 4
            celsius = Math.Round(celsius, 4);
            tbCelsius.Text = celsius.ToString();

            kelvin = (farenheit - 32) / 1.8 + 273.15;
            //Math.Round limits the decimal position to 4
            kelvin = Math.Round(kelvin, 4);
            tbKelvin.Text = kelvin.ToString();
        }
        //Method will convert a value from Celsius to Farenheit and Kelvin
        private void convertCelsius()
        {
            //Variable declaration
            double farenheit = 0;
            double celsius = 0;
            double kelvin = 0;

            //double.Parse instruction will convert content from the text field to a double type number
            celsius = double.Parse(tbCelsius.Text);

            //Math operations are executed to convert temperature from Celsius to Farenheit and Kelvin
            farenheit = celsius * 1.8 + 32;
            //Math.Round limits the decimal position to 4
            farenheit = Math.Round(farenheit, 4);
            tbFarenheit.Text = farenheit.ToString();

            kelvin = celsius + 273.15;
            //Math.Round limits the decimal position to 4
            kelvin = Math.Round(kelvin, 4);
            tbKelvin.Text = kelvin.ToString();
        }
        //Method will convert a value from Kelvin to Farenheit and Celsius
        private void convertKelvin()
        {
            //Variable declaration
            double farenheit = 0;
            double celsius = 0;
            double kelvin = 0;

            //double.Parse instruction will convert content from the text field to a double type number
            kelvin = double.Parse(tbKelvin.Text);

            //Math operations are executed to convert temperature from Kelvin to Farenheit and Celsius
            farenheit = (kelvin - 273.15) * 1.8 + 32;
            //Math.Round limits the decimal position to 4
            farenheit = Math.Round(farenheit, 4);
            tbFarenheit.Text = farenheit.ToString();

            celsius = kelvin - 273.15;
            //Math.Round limits the decimal position to 4
            celsius = Math.Round(celsius, 4);
            tbCelsius.Text = celsius.ToString();
        }
        private void btnConvert_Click(object sender, EventArgs e)
        {
            //This instruction determines which textfield has information, then it is validated that is a digit and finally the conversion begins
            if (onlyOneTextfieldFilled())
            {
                if (!string.IsNullOrEmpty(tbFarenheit.Text) && double.TryParse(tbFarenheit.Text, out _))
                {
                    //Method is called to convert temperature to other measure units
                    convertFarenheit();
                }
                else if (!string.IsNullOrEmpty(tbCelsius.Text) && double.TryParse(tbCelsius.Text, out _))
                {
                    //Method is called to convert temperature to other measure units
                    convertCelsius();
                }
                else if (!string.IsNullOrEmpty(tbKelvin.Text) && double.TryParse(tbKelvin.Text, out _))
                {
                    //Method is called to convert temperature to other measure units
                    convertKelvin();
                }
                else
                {
                    //if it's not a number, program deletes all data from the fields and shows a message for the user
                    clearFields();
                    MessageBox.Show("Only numbers accepted. Try Again");
                }
            }
            else
            {
                //if there is data on all fields, program deletes all data from the fields and shows a message for the user
                clearFields();
                MessageBox.Show("Please write only in one field.");
            }
        }

        private void lblCelcius_Click(object sender, EventArgs e)
        {

        }
        //Clicking this button will delete all content from the textfields
        private void btnDelete_Click(object sender, EventArgs e)
        {
            clearFields();
        }

        //This next method saves the temperature to the clipboard
        private void btnCopyFarenheit_Click(object sender, EventArgs e)
        {
            //This code verifies if the field has data and saves it to the clipboard, if it's empty it shows a message
            if (!string.IsNullOrEmpty(tbFarenheit.Text))
            {
                Clipboard.SetText($"{tbFarenheit.Text}°F");
                MessageBox.Show($"{tbFarenheit.Text}°F, Copied!");
            }
            else
            {
                MessageBox.Show("There is no data for Farenheit");
            }
        }

        private void btnCopyCelsius_Click(object sender, EventArgs e)
        {
            //This code verifies if the field has data and saves it to the clipboard, if it's empty it shows a message
            if (!string.IsNullOrEmpty(tbCelsius.Text))
            {
                Clipboard.SetText($"{tbCelsius.Text}°C");
                MessageBox.Show($"{tbCelsius.Text}°C, Copied!");
            }
            else
            {
                MessageBox.Show("There is no data for Celsius");
            }
        }

        private void btnCopyKelvin_Click(object sender, EventArgs e)
        {
            //This code verifies if the field has data and saves it to the clipboard, if it's empty it shows a message
            if (!string.IsNullOrEmpty(tbKelvin.Text))
            {
                Clipboard.SetText($"{tbKelvin.Text}K");
                MessageBox.Show($"{tbKelvin.Text}K, Copied!");
            }
            else
            {
                MessageBox.Show("There is no data for Kelvin");
            }
        }
    }
}